ANSI_FOREGROUND_BLACK=\033[30m
ANSI_FOREGROUND_RED=\033[31m
ANSI_FOREGROUND_GREEN=\033[32m
ANSI_FOREGROUND_YELLOW=\033[33m
ANSI_FOREGROUND_BLUE=\033[34m
ANSI_FOREGROUND_MAGENTA=\033[35m
ANSI_FOREGROUND_CYAN=\033[36m
ANSI_FOREGROUND_WHITE=\033[37m
ANSI_BACKGROUND_BLACK=\033[40m
ANSI_BACKGROUND_RED=\033[41m
ANSI_BACKGROUND_GREEN=\033[42m
ANSI_BACKGROUND_YELLOW=\033[43m
ANSI_BACKGROUND_BLUE=\033[44m
ANSI_BACKGROUND_MAGENTA=\033[45m
ANSI_BACKGROUND_CYAN=\033[46m
ANSI_BACKGROUND_WHITE=\033[47m

ANSI_BOLD=\033[1m

ANSI_RESET=\033[0m
define err
	@echo -e "$(ANSI_BACKGROUND_RED)$(ANSI_FOREGROUND_WHITE)$(1)$(ANSI_RESET)"
endef

define success
	@echo -e "$(ANSI_BACKGROUND_GREEN)$(ANSI_FOREGROUND_BLACK)$(ANSI_BOLD)$(1)$(ANSI_RESET)"
endef

define note
	@echo -e "$(ANSI_BACKGROUND_YELLOW)$(ANSI_FOREGROUND_BLACK)$(ANSI_BOLD)$(1)$(ANSI_RESET)"
endef

define job
	@echo -e "$(ANSI_BACKGROUND_BLUE)$(ANSI_FOREGROUND_WHITE)$(ANSI_BOLD)$(1)$(ANSI_RESET)"
endef
